version: '3'
services:
  ruby:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - 8080:80
    command: ""
    environment:
      SINATRA_DB: 'postgis://db/craigslistscrape'
      CRAIGSLIST_URL: 'https://raleigh.craigslist.org'
  db:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - ./db_dumps:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: 'craigslistscrape'
      POSTGRES_USER: 'root'
    ports:
      - 5432:5432
