source "https://rubygems.org"

gem 'pg'
gem 'sinatra'
gem 'thin'
gem 'activerecord-postgis-adapter'
gem 'sinatra-activerecord'
gem 'rake'
gem 'json'
gem 'dotenv'
gem 'redis'
gem 'postgres_ext'
# gem 'rgeo-geojson'
gem 'shotgun'

gem 'resque'
gem 'resque-scheduler'
gem 'resque-slack'
gem 'foreman'
gem 'rspec'
